### ISSUE TITLE
missing `aws_account_id` entry in the project varset

### ISSUE THREAD

**Issue by chebelom** [djschnei21/multi-product-integration-demo#2]
thank you for this repo, amazing job.
I am trying it and I think that the TF var `aws_account_id` is missing in the project varset.
it is required by the doormat provider to authenticate and create the AWS resources.

if you confirm that it is not something I am missing somewhere else, I'll send a PR soon.

![image](https://github.com/djschnei21/multi-product-integration-demo/assets/11653136/3c5b204d-e382-4b88-aa67-a66c0af9f4ad)

**Comment by djschnei21** [comment]
ah, thanks for the catch!  Looks like I missed that in the README table.  Updated!
