### ISSUE TITLE
Nomad Workload Identity

### ISSUE THREAD

**Issue by assareh** [djschnei21/multi-product-integration-demo#4]
Great work! I wanted to let you know I updated the Nomad Vault integration to use Workload Identity instead of token role in my fork [here](https://github.com/djschnei21/multi-product-integration-demo/compare/main...assareh:multi-product-integration-demo:main). Workload Identity was introduced in Nomad 1.7. ([Blog](https://www.hashicorp.com/blog/nomad-1-7-improves-vault-and-consul-integrations-adds-numa-support))

I also modified the workload example to use Workload Identity as well [here](https://github.com/djschnei21/terraform-nomad-workload/compare/main...assareh:terraform-nomad-workload:main). 

The other changes were due to linting with terraform fmt.

**Comment by djschnei21** [comment]
Amazing! Has been on my to-do list for too long, I really appreciate it. Mind opening a PR?

**Comment by assareh** [comment]
Done, https://github.com/djschnei21/multi-product-integration-demo/pull/5

**Comment by djschnei21** [comment]
thanks Andy (and sorry for the massive delay)

**Comment by djschnei21** [comment]
thanks Andy (and sorry for the massive delay)
